name: get_flutter_fire
version: 1.0.0+1
publish_to: none
description: Boilerplate for Flutter with GetX, showing sample utilization of Firebase capabilities
environment: 
  sdk: '>=3.3.4 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  flutter: 
    sdk: flutter
  firebase_core: ^2.32.0
  firebase_ui_auth: ^1.14.0
  firebase_auth: ^4.20.0
  google_sign_in: ^6.2.1
  firebase_ui_oauth_google: ^1.3.2
  google_fonts: ^6.2.1
  firebase_storage: ^11.7.5
  image_picker: ^1.1.1
  file_picker: ^8.0.3
  path: ^1.9.0
  get_storage: ^2.1.1
  firebase_ui_localizations: ^1.12.0
  firebase_remote_config: ^4.4.7
  firebase_analytics: ^10.10.7

dev_dependencies: 
  flutter_lints: 3.0.2
  flutter_test: 
    sdk: flutter

flutter: 
  fonts:
    - family: SocialIcons
      fonts:
        - asset: packages/firebase_ui_auth/fonts/SocialIcons.ttf
  assets:
    - assets/images/flutterfire_300x.png
    - assets/images/dash.png
    - assets/icons/logo.png
  uses-material-design: true

